'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import styles from './AdminLogin.module.css'

export default function AdminLogin({ role = 'admin' }) {
  const router = useRouter(); const isAdmin = role === 'admin'
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState({}); const [loading, setLoading] = useState(false)
  function updateEmail(event) { setEmail(event.target.value); setFieldErrors((current) => ({ ...current, email: '' })); setError('') }
  function updatePassword(event) { setPassword(event.target.value); setFieldErrors((current) => ({ ...current, password: '' })); setError('') }
  async function submit(event) {
    event.preventDefault(); const nextErrors = {}
    if (!email.trim()) nextErrors.email = 'Enter the email address for your account.'
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email.trim())) nextErrors.email = 'Use a valid email address, such as name@example.com.'
    if (!password) nextErrors.password = 'Enter your password to continue.'
    if (Object.keys(nextErrors).length) { setFieldErrors(nextErrors); return }
    setError(''); setFieldErrors({}); setLoading(true)
    try { const response = await fetch(isAdmin ? '/api/auth/admin/login' : '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email.trim(), password }) }); if (!response.ok) { setError(response.status === 401 ? 'We couldn’t sign you in with that email and password. Check your details and try again.' : response.status === 429 ? 'Too many sign-in attempts. Please wait a few minutes before trying again.' : 'We’re unable to sign you in right now. Please try again in a moment.'); return }; const next = new URLSearchParams(window.location.search).get('next'); const portal = isAdmin ? '/admin' : '/user'; router.push(next?.startsWith(`${portal}/`) && !next.startsWith('//') ? next : portal); router.refresh() } catch { setError('We couldn’t reach the sign-in service. Check your connection and try again.') } finally { setLoading(false) }
  }
  const workspace = isAdmin ? 'OWNER WORKSPACE' : 'MY FUNDING'; const headline = isAdmin ? 'Manage funding with confidence.' : 'Keep your funding moving.'; const description = isAdmin ? 'Review applications, manage account activity, and keep your lending operation moving from one secure workspace.' : 'Check your application, funding status, and loan details from one simple account.'; const benefits = isAdmin ? ['Review applicant decisions', 'Manage account credits and debits', 'Monitor your funding pipeline'] : ['Track your application', 'View your loan and payments', 'Message your funding team']
  return <main className={`${styles.page} ${isAdmin ? styles.admin : styles.user}`}><section className={styles.intro}><Link href="/" className={styles.brand}><i>G</i> Small Business Application</Link><div className={styles.introCopy}><p>{workspace}</p><h1>{headline}</h1><span>{description}</span><ul>{benefits.map((benefit) => <li key={benefit}><i>✓</i>{benefit}</li>)}</ul></div><small>Small business funding · {isAdmin ? 'Owner access' : 'Borrower access'}</small></section><section className={styles.signIn}><div className={styles.card}><Link href="/" className={styles.back}>← Back to website</Link><div className={styles.cardIcon}>{isAdmin ? '⌘' : '⌂'}</div><p>{isAdmin ? 'ADMIN ACCESS' : 'ACCOUNT LOGIN'}</p><h2>Welcome back</h2><span>Sign in to access your {isAdmin ? 'owner workspace' : 'funding account'}.</span><form onSubmit={submit} noValidate><label>Email address<input type="email" value={email} onChange={updateEmail} placeholder="you@company.com" autoComplete="email" autoFocus aria-invalid={Boolean(fieldErrors.email)} aria-describedby={fieldErrors.email ? 'login-email-error' : undefined} />{fieldErrors.email && <small id="login-email-error" className={styles.fieldError} role="alert">{fieldErrors.email}</small>}</label><label>Password<div className={styles.passwordField}><input type={showPassword ? 'text' : 'password'} value={password} onChange={updatePassword} placeholder="Enter your password" autoComplete="current-password" aria-invalid={Boolean(fieldErrors.password)} aria-describedby={fieldErrors.password ? 'login-password-error' : undefined} /><button type="button" onClick={() => setShowPassword((current) => !current)}>{showPassword ? 'Hide' : 'Show'}</button></div>{fieldErrors.password && <small id="login-password-error" className={styles.fieldError} role="alert">{fieldErrors.password}</small>}</label>{error && <div className={styles.error} role="alert">{error}</div>}<div className={styles.formFooter}><label className={styles.remember}><input type="checkbox" />Remember me</label></div><button type="submit" className={styles.submit} disabled={loading}>{loading ? 'Signing in…' : <>Sign in <b>→</b></>}</button>{!isAdmin && <p className={styles.applyPrompt}>Don’t have an account? <Link href="/apply">Start an application</Link></p>}</form></div></section></main>
}
